name: publish NPM

on:
  # schedule:
    # - cron: '0 10 * * *' # everyday at 10am
  push:
    # branches:
    #   - '**'
    tags:
      - 'v*.*.*'
  # pull_request:
  #   branches:
  #     - 'master'

jobs:
  publish:
    name: Publish NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: install dependencies
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        env:
          NODE_ENV: production
        run: npm run build
      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
